# Settings under "global" pertain to all components
# of the Consul installation.
global:
  # The name of your installation. This should always
  # be set to consul.
  name: consul
  # Enable metrics so you can observe what's happening
  # in your installation.
  metrics:
    enabled: true
  # Consul image.
  image: hashicorp/consul:1.11.5

# Settings under "server" configure Consul servers.
server:
  # replicas sets the number of servers.
  # In production, this should be 3 or 5, however
  # for testing, this should be set to 1.
  replicas: 1

# Enable Consul's service mesh functionality.
connectInject:
  enabled: true

# Settings under "controller" configure Consul's controller
# that manages CRDs (Custom Resource Definitions).
# CRDs are covered in later chapters.
controller:
  enabled: true

# Install Prometheus, a metrics database.
prometheus:
  enabled: true

# Settings under "ui" configure the Consul UI.
ui:
  service:
    # Use a load balancer service in
    # front of the Consul UI so we can access it using
    # minikube tunnel.
    type: LoadBalancer
    # Use port 8500 for the UI.
    port:
      http: 8500
