global:
  name: consul
  metrics:
    enabled: true
  imageK8S: ghcr.io/consul-up/k8s-cp:0.41.1-1

server:
  replicas: 1

connectInject:
  enabled: true

controller:
  enabled: true

prometheus:
  enabled: true

ui:
  service:
    type: LoadBalancer
    port:
      http: 8500

ingressGateways:
  enabled: true
  defaults:
    affinity: null
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer
        ports:
          - port: 8080
      replicas: 1
